database/models.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from common.exts import db

__all__ = ['User']


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), nullable=False)
    password = db.Column(db.String(50), nullable=False)
    profile = db.relationship('Profile', backref='user', uselist=False, cascade='delete')


class Profile(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(100), nullable=False, unique=True)
    address = db.Column(db.String(255))
    phone = db.Column(db.String(20))
    uid = db.Column(db.Integer, db.ForeignKey('user.id'))


def load_data():
    db.session.query(User).delete()
    for i in range(5):
        user = User(username=f'user{i}', password='password')
        user.profile = Profile(address='Shanghai', phone='13816807866', email=f'user{i}@me.com')
        db.session.add(user)
    db.session.commit()

common/__init__.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import Flask
from database import db_bp
from .exts import bootstrap, db


def create_app(config, name):
    app = Flask(name)
    app.config.from_object(config)
    return app


def register_bps(app):
    app.register_blueprint(db_bp, url_prefix='/db')


def register_exts(app):
    bootstrap.init_app(app)
    db.init_app(app)

database/__init__.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask_bootstrap import Blueprint

db_bp = Blueprint('db', __name__)

from . import views
from . import models

database/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import render_template, url_for, redirect
from flask.views import MethodView

from common.exts import db
from database import db_bp
from database.models import User, load_data


class HomeView(MethodView):
    def get(self):
        return render_template('database/index.html', users=User.query.all())


class UserView(MethodView):
    def get(self, id):
        User.query.filter_by(id=id).delete()
        db.session.commit()
        return redirect(url_for('db.home'))


def load():
    load_data()
    return redirect(url_for('db.home'))


db_bp.add_url_rule('/', view_func=HomeView.as_view('home'))
db_bp.add_url_rule('/load', view_func=load, endpoint='load')
db_bp.add_url_rule('/user/<int:id>', view_func=UserView.as_view('user'))

main.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import render_template
from common import create_app, register_bps, register_exts
import config

app = create_app(config, __name__)
register_bps(app)
register_exts(app)

app.add_url_rule('/', endpoint='index', view_func=lambda: render_template('index.html'))

if __name__ == '__main__':
    app.run()

templates/base.html
{% extends 'bootstrap/base.html' %}

{% import 'bootstrap/utils.html' as utils %}
{% import "bootstrap/wtf.html" as wtf %}

{% block html_attribs %} lang="zh"{% endblock %}

{% block styles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}">
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Flask 学习测试平台</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('index')}}">首页<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('db.load')}}">加载数据</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          数据模型
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% endblock %}

{% block content %}
<div class="main">
    {% block main %}{% endblock %}
</div>
{% endblock %}

templates/database/index.html
{% extends 'base.html' %}
{% block main %}
<h3 align="left">用户表数据</h3>
<table class="table table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th>ID</th>
        <th>用户名</th>
        <th>邮箱</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
    <tr>
        <td>{{user.id}}</td>
        <td>{{user.username}}</td>
        <td>{{user.profile.email}}</td>
        <td><a href="{{url_for('db.user', id=user.id)}}" class="">删除</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block main %}
<h2 align="center">测试项</h2>
<hr>
<li>
    <a href="{{url_for('db.home')}}" class="">数据库测试</a></h2>
</li>
{% endblock %}